version: "3.8"

services:
  telegram_bot:
    build: telegram_bot/
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - api_key=
      - pay_token=
      - server_url=
  backend:
    build: backend_/
    ports:
      - 8000:8000
    depends_on:
      - redis
    networks:
      - app-network
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge