# Generated by Django 5.0.4 on 2024-04-30 07:37

import qrs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(max_length=1000)),
                ('qr_code', models.ImageField(null=True, upload_to=qrs.models.save_basic_qr_code)),
            ],
        ),
    ]
